# Generated by Django 2.2.1 on 2019-08-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190802_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalstats',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='totalstats',
            name='date_updated',
            field=models.DateField(null=True),
        ),
    ]
